import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  reactCompiler: true,

  images: {
    domains: [
      "imagez.tmz.com",
      "assets1.cbsnewsstatic.com",
      "assets1.cbsnewsstatic.com",
      "www.politico.com",
      "platform.theverge.com",
      "media.cnn.com",
      "ichef.bbci.co.uk",
      "assets2.cbsnewsstatic.com",
      "assets3.cbsnewsstatic.com",
      "npr.brightspotcdn.com",
      "cdn.mos.cms.futurecdn.net",
      "i.abcnewsfe.com",
      "images.axios.com",
      "images.wsj.net",
      "www.washingtonpost.com",
      "www.instyle.com",
      "dims.apnews.com",
      "www.investors.com",
      "i0.wp.com",
      "www.wcia.com",
      "www.investopedia.com",
      "nypost.com",
      "www.cnet.com",
      "thegamepost.com",
      "images.rpgsite.net",
      "www.pcgamesn.com",
      "assets.bwbx.io",
      "www.jalopnik.com",
      "helios-i.mashable.com",
      "kotaku.com",
      "www.bgr.com",
      "substackcdn.com",
      "techcrunch.com",
      "images.nintendolife.com",
      "www.rollingstone.com",
      "ufc.com",
      "media-cldnry.s-nbcnews.com",
      "cdn.arstechnica.net",
      "twistedvoxel.com",
      "www.notebookcheck.net",
      "www.sciencealert.com",
      "media.theshow.com",
      "www.pcworld.com",
      "s100.iracing.com",
      "s.yimg.com",
      "fortune.com",
      "i.insider.com",
      "images.ft.com",
    ],
  },
};

export default nextConfig;
